;;; -*- coding: utf-8 -*-
(("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/AgendaTickler.org" . 1010)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/Bookmarks.org" . 809)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/Contacts.org" . 1139)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/GTD.org" . 47580)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/Inbox.org" . 9845)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/References.org" . 51517)
 ("/home/utilisateur/.emacs.dAutreOrdi/config.org" . 115106)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisationsAvecDep.org" . 5529)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/recentf-save.el" . 8776)
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/Lessauvegardes.org" . 5108)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/integration.org" . 3707)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisations.org" . 27737)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisationsAvecDep.sh" . 445)
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/test.org" . 53)
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/Lessauvegardes.org"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/flycheck-grammalecte-autoloads.el" . 2520)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/grammalecte.el" . 9890)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/grammalecte.el"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/grammalecte/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte/grammalecte/README.txt"))
 ("/home/utilisateur/.dotfiles/.emacs.d/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight"))
 ("/home/utilisateur/.dotfiles/.emacs.d/config/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisations.org"))
 ("/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisationsAvecDep.el" . 1686)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/org-mode.org" . 60447)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/Inbox.org"))
 ("/home/utilisateur/.emacs.dAutreOrdi/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/config.org"))
 ("/home/utilisateur/sharedDirectoryPrivate/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel"))
 ("/home/"
  (dired-filename . "/home/utilisateur"))
 ("/home/utilisateur/.emacs.d/straight/"
  (dired-filename . "/home/utilisateur/.emacs.d/straight/build"))
 ("/home/utilisateur/.emacs.d/straight/build/"
  (dired-filename . "/home/utilisateur/.emacs.d/straight/build/flycheck-grammalecte"))
 ("/home/utilisateur/.dotfiles/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/build"))
 ("/home/utilisateur/.emacs.d/straight/build/flycheck-grammalecte/flycheck_grammalecte.py" . 8058)
 ("/home/utilisateur/.emacs.d/straight/build/flycheck-grammalecte/"
  (dired-filename . "/home/utilisateur/.emacs.d/straight/build/flycheck-grammalecte/grammalecte.el"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/build/flycheck-grammalecte"))
 ("/home/utilisateur/Téléchargements/" . 510)
 ("/home/utilisateur/"
  (dired-filename . "/home/utilisateur/.emacs.d"))
 ("/home/utilisateur/.emacs.d/"
  (dired-filename . "/home/utilisateur/.emacs.d/straight"))
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/ordi/" . 623)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/custom.el" . 1599)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/xah-fly-keys/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/repos/xah-fly-keys/.git"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/straight/repos/xah-fly-keys"))
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/Bookmarks.html" . 19355)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/org-download/org-download-autoloads.el" . 396)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/contacts.org"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/orgzly/Contacts.vcf" . 12)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/images/Testn/" . 603)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/images/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/org/images/Testn"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/org/images"))
 ("/home/utilisateur/.dotfiles/.emacs.d/config.org" . 9996)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/testimage.org"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/testimage.org" . 239)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/org-download/org-download.el" . 16693)
 ("/home/utilisateur/.dotfiles/.emacs.d/LEinit.el" . 1233)
 ("/home/utilisateur/.dotfiles/.emacs.d/Awesome.org" . 48058)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/savehist.el" . 848)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/main/comment_je_vais_faire_mon_braindump.org" . 456)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/reference/BiaisAutocomplaisance2021.org" . 255)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/artistes.org" . 115)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/evenement.org" . 11)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/image.org" . 22)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/next.org" . 8)
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/Monreadme.org" . 119)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/leo_ferre.org" . 3632)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/journal_de_dissatisfaction.org" . 25)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/différences_émotion_ressenti_sentiments_etc.org" . 1648)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/dialectique.org" . 3227)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/descartes.org" . 483)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/beethoven.org" . 6842)
 ("/home/utilisateur/sharedDirectoryPrivate/orgzlyBisTest/Gab.org" . 5159)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/TD1/Exercices.org" . 1924)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/sujet2/Exercices.org" . 2707)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/artistes.org" . 7593)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/notesPerso(nepasgarderPointDinterogation)/films_vus.org" . 2667)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/.dir-locals.el" . 130)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/notesPerso(nepasgarderPointDinterogation)"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/notesPerso(nepasgarderPointDinterogation)/" . 651)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/journal_de_dissatisfaction.org" . 3035)
 ("/home/utilisateur/.emacs.dAutreOrdi/#config.org#" . 115972)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/match-string" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/file.read-lines" . 70)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/word-or-region" . 86)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/and" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/save-excursion" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/with-current-buffer" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/forward-char" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/set-file-modes" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/aset" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/delete-region" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/delete-char" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/file-name-directory" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/match-beginning" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/file-relative-name" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/thing-at-point" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/copy-file" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/point" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/mapc" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/string=" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/region-end" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/match-end" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/copy-directory" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/make-local-variable" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/end-of-line" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/file.process" . 80)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/interactive" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/set-mark" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/find-file" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/widget-get" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/re-search-backward" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/search-backward-regexp" . 41)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/kill-buffer" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/region-active-p" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/number-to-string" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/bounds-of-thing-at-point" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/not" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/global-set-key" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/search-forward-regexp" . 41)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/search-forward" . 41)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/aref" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet-snippets/snippets/emacs-lisp-mode/delete-directory" . 40)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/nov/nov-autoloads.el" . 508)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/esxml/esxml-autoloads.el" . 634)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/kv/kv-autoloads.el" . 287)
 ("/tmp/"
  (dired-filename . "/tmp/systemd-private-7787502c020c43ae83a47f933326a941-systemd-resolved.service-ZFFIfi"))
 ("/home/utilisateur/.emacs.d/var/"
  (dired-filename . "/home/utilisateur/.emacs.d/var/custom.el"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/Nom_de_l'image/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/Nom_de_l'image/2022-03-09_13-29-17_floating_house_by_deniszhbankov_df04lx0-fullview.jpg"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/build/org-download/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/straight/build/org-download/org-download.el"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/build/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/straight/build/org-download"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/straight/repos"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-download/org-download.el" . 27571)
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-download/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-download/org-download.el"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/"
  (dired-filename . "/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-download"))
 ("/"
  (dired-filename . "/home"))
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-roam/doc/org-roam.texi" . 53708)
 ("/home/utilisateur/.emacs.dAutreOrdi/var/backup/!home!msi!.emacs.d!config.org.~113~" . 51540)
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-download/README.md" . 514)
 ("/home/utilisateur/.emacs.dAutreOrdi/var/backup/!home!msi!.emacs.dclean!config.org.~1~" . 48504)
 ("/home/utilisateur/.emacs.dAutreOrdi/var/backup/!home!msi!.emacs.d!config.org.~112~" . 89454)
 ("/home/utilisateur/.emacs.dAutreOrdi/var/auto-save/#!home!msi!.emacs.d(copie 27.2)!config.org#" . 85555)
 ("/home/utilisateur/.emacs.dAutreOrdi/var/auto-save/#!home!msi!.emacs.d!config.org#" . 48648)
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/build-cache.el" . 18)
 ("/home/utilisateur/.emacs.dAutreOrdi/straight/repos/org-roam/doc/org-roam.org" . 46037)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/org/artistesImages/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/org/artistesImages/Aenami"))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/async/async-autoloads.el" . 6140)
 ("/home/utilisateur/.dotfiles/.emacs.d/lisp/LayerXahFlyKey/LayerXahFlyKey.org" . 27219)
 ("/media/"
  (dired-filename . "/media/utilisateur"))
 ("/media/utilisateur/"
  (dired-filename . "/media/utilisateur/8726733b-80c1-4ed4-9915-ed73e21cab26"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/àFairePetitÀPetit/snippets/Image" . 141)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/àFairePetitÀPetit/snippets/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/àFairePetitÀPetit/snippets/Image"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/àFairePetitÀPetit/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/templatesOrgCapture/àFairePetitÀPetit/.."))
 ("/home/utilisateur/.emacs.dAutreOrdi/init.el" . 16423)
 ("/home/utilisateur/.emacs.dAutreOrdi/config.el" . 29164)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/peep-dired/peep-dired-autoloads.el" . 706)
 ("/home/utilisateur/.emacs.d/config/"
  (dired-filename . "/home/utilisateur/.emacs.d/config/basicOptimisationsAvecDep.org"))
 ("/home/utilisateur/sharedDirectoryPrivate/agendapourgoogle.ics" . 2667)
 ("/home/utilisateur/.dotfiles/.emacs.d/Readme.org" . 3838)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/org-mode.el" . 32636)
 ("/home/utilisateur/.bashrc" . 3648)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/articles/" . 245)
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/main/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/main/comment_je_vais_faire_mon_braindump.org"))
 ("/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/reference/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/notes/zettelkasten/reference/BiaisAutocomplaisance2021.org"))
 ("/home/utilisateur/mesdocuments/"
  (dired-filename . "/home/utilisateur/mesdocuments/personnel"))
 ("/home/utilisateur/mesdocuments/personnel/"
  (dired-filename . "/home/utilisateur/mesdocuments/personnel/informatique"))
 ("/home/utilisateur/mesdocuments/personnel/informatique/"
  (dired-filename . "/home/utilisateur/mesdocuments/personnel/informatique/mesSitesWeb"))
 ("/home/utilisateur/mesdocuments/personnel/informatique/mesSitesWeb/"
  (dired-filename . "/home/utilisateur/mesdocuments/personnel/informatique/mesSitesWeb/Netlify"))
 ("/home/utilisateur/.dotfiles/Readme.org" . 22)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/programmation.org" . 3226)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/AlgoII"))
 ("/home/utilisateur/sharedDirectoryPrivate/.stfolder/" . 227)
 ("/home/utilisateur/.dotfiles/.emacs.d/init.el" . 413)
 ("/home/utilisateur/.dotfiles/.emacs.d/Organisation.jpg" . 614)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/Projet"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/Projet/application_campus/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/Projet/application_campus/.gitignore"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/Projet/Readme.md" . 411)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/ProjetPrepIsima/Projet/" . 468)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/org-contrib/org-contacts.el" . 41223)
 ("/home/utilisateur/Documents/"
  (dired-filename . "/home/utilisateur/Documents/.."))
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/org-vcard/org-vcard.el" . 30426)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/contacts.vcf" . 197)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/magit/magit-autoloads.el" . 93325)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/git-commit/git-commit-autoloads.el" . 635)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/with-editor/with-editor-autoloads.el" . 3467)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!init.el.~3~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~4~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~1~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build-cache.el" . 38572)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/basicOptimisations.el" . 3742)
 ("/home/utilisateur/.dotfiles/.emacs.d/LEconfig.org" . 8793)
 ("/home/utilisateur/.dotfiles/.emacs.d/config.el" . 7177)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~4~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!configAvecCitarPasPropre.org.~1~" . 2284)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~6~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~1~" . 3127)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~18~" . 2553)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~19~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~3~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config!config.org.~3~" . 3988)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~2~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~7~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~243~" . 961)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~8~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~20~" . 2555)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.damaury!config.org.~1~" . 2238)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~22~" . 2557)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~250~" . 1846)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~7~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~21~" . 3214)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~24~" . 2556)
 ("/home/utilisateur/.dotfiles/.emacs.d/lisp/LayerXahFlyKey/LayerXahFlyKey.el" . 3142)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~1~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!lisp!LayerXahFlyKey!LayerXahFlyKey.org.~4~" . 5038)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~1~" . 10450)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~245~" . 961)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~14~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!init.el.~1~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~8~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~247~" . 1008)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~5~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~17~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.dc!init.el.~1~" . 261)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~18~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~19~" . 2554)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~5~" . 10093)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~4~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config.org.~2~" . 1896)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~5~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~244~" . 961)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~16~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~2~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config!config.org.~2~" . 2292)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~10~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~242~" . 961)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~248~" . 1813)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~2~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~22~" . 3214)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~21~" . 2556)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~2~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~6~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config!basicOptimisations.org.~3~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~16~" . 2553)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~3~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config!config.org.~1~" . 2292)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~4~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~2~" . 10093)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~4~" . 10093)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/build/straight/straight-autoloads.el" . 15359)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/treemacs/README.org" . 19902)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/flycheck/flycheck.el" . 54542)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org-ql/makem.sh" . 15409)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/emacs-request/request.el" . 1718)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/use-package/use-package.org" . 23053)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/use-package/README.md" . 21670)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/use-package/use-package-core.el" . 32396)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/use-package/use-package.texi" . 25110)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/use-package/use-package-tests.el" . 15605)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/emacsql/emacsql-sqlite.el" . 1500)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet/NEWS" . 12145)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/yasnippet/yasnippet.el" . 5731)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~6~" . 1885)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~3~" . 3127)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~3~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!lisp!LayerXahFlyKey!LayerXahFlyKey.org.~2~" . 5325)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~10~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~23~" . 2557)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~20~" . 3214)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~6~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/melpa/Makefile" . 3219)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!init.el.~2~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~1~" . 3127)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!lisp!LayerXahFlyKey!LayerXahFlyKey.org.~6~" . 5065)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~5~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~2~" . 3127)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/xah-elisp-mode/xah-elisp-mode.el" . 54919)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config.org.~3~" . 2557)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.dotfiles!.emacs.d!config.org.~1~" . 1876)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~5~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~3~" . 10093)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~11~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/no-littering/README.md" . 310)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/no-littering/no-littering.el" . 1194)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org-roam/org-roam-compat.el" . 4954)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config.org.~17~" . 2553)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~4~" . 3125)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~5~" . 329)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~8~" . 261)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~7~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~249~" . 1846)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/straight.el/install.el" . 5323)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/straight.el/README.md" . 9569)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~1~" . 332)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/straight.el/straight.el" . 22061)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/prescient.el/prescient.el" . 2784)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!init.el.~9~" . 261)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~9~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~246~" . 961)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~12~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!init.el.~6~" . 260)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!utilisateur!.emacs.d!config!basicOptimisations.org.~15~" . 3124)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/ts.el/makem.sh" . 15769)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/projectile/projectile.el" . 8317)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!config.org.~6~" . 10093)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!lisp!LayerXahFlyKey!LayerXahFlyKey.org.~3~" . 5039)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/backup/!home!msi!.emacs.d!lisp!LayerXahFlyKey!LayerXahFlyKey.org.~5~" . 5065)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/dap-mode/dap-utils.el" . 2439)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/dap-mode/dap-netcore.el" . 1155)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/el-get/el-get-install.el" . 794)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/el-get/el-get-custom.el" . 1127)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org-super-agenda/makem.sh" . 14747)
 ("/home/utilisateur/.dotfiles/.emacs.d/lisp/org-mode/lisp/org-persist.el" . 8424)
 ("/home/utilisateur/.dotfiles/.emacs.d/lisp/org-mode/lisp/org-id.el" . 7798)
 ("/home/utilisateur/.dotfiles/.emacs.d/lisp/org-mode/lisp/org-clock.el" . 8570)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-java/test/windows-bootstrap.el" . 869)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/flycheck/doc/conf.py" . 3638)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/flycheck/doc/languages.rst" . 10821)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/flycheck/test/flycheck-test.el" . 18198)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-treemacs/test/windows-bootstrap.el" . 1307)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/citar/test/install.el" . 211)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-ui/test/windows-bootstrap.el" . 1476)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/straight.el/benchmark/straight-bench.el" . 2602)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org-contrib/lisp/org-track.el" . 2360)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/projectile/test/projectile-test.el" . 87871)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org/lisp/org-persist.el" . 8424)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/dap-mode/test/windows-bootstrap.el" . 1501)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org/lisp/org-id.el" . 7798)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/org/lisp/org-clock.el" . 8570)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/magit/lisp/magit-apply.el" . 2169)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/el-get/test/el-get-tests.el" . 1051)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-mode/test/windows-bootstrap.el" . 1469)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-mode/test/test-packages.el" . 3882)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-mode/clients/lsp-magik.el" . 2673)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/lsp-mode/clients/lsp-php.el" . 13234)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/dimmer.el/doc/gallery.el" . 264)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/treemacs/src/elisp/treemacs-persistence.el" . 1364)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/treemacs/src/elisp/treemacs-customization.el" . 23564)
 ("/home/utilisateur/.dotfiles/.emacs.d/straight/repos/el-get/recipes/emms.rcp" . 238)
 ("/home/utilisateur/.emacs.d/var/recentf-save.el" . 7748)
 ("/home/utilisateur/.emacs.d/init.el" . 1027)
 ("/home/utilisateur/.emacs.d/config/basicOptimisationsAvecDep.org" . 1109)
 ("/home/utilisateur/.dotfiles/.gitconfig" . 55)
 ("/home/utilisateur/.dotfiles/.stow-local-ignore" . 28)
 ("/home/utilisateur/.emacs.d/straight/build/ox-hugo/ox-hugo-autoloads.el" . 9915)
 ("/home/utilisateur/.emacs.d/straight/build/magit-section/magit-section-autoloads.el" . 421)
 ("/home/utilisateur/.dotfiles/.emacs.d/var/"
  (dired-filename . "/home/utilisateur/.dotfiles/.emacs.d/var/eww"))
 ("/home/utilisateur/.dotfiles/.emacs.d/config/try.org" . 27)
 ("/home/utilisateur/.dotfiles/.emacs.d/config/raccourcis.org" . 3709)
 ("/home/utilisateur/.emacs.d/etc/"
  (dired-filename . "/home/utilisateur/.emacs.d/etc/yasnippet"))
 ("/home/utilisateur/.bash_history" . 10448)
 ("/home/utilisateur/.ssh/id_rsa.pub" . 733)
 ("/home/utilisateur/.ssh/"
  (dired-filename . "/home/utilisateur/.ssh/id_rsa.pub"))
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/css/theme.css" . 1249)
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/css/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/org-linkz/css/theme.css"))
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/js/main.js" . 578)
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/js/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/org-linkz/js/main.js"))
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/org-linkz/js"))
 ("/home/utilisateur/mesdocuments/professionnel/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/TechnoDuWeb/TP/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/TechnoDuWeb/TP/1"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/TechnoDuWeb/Projetweb/" . 1415)
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/TechnoDuWeb/" . 660)
 ("/home/utilisateur/Testdedossier/test.c" . 72)
 ("/home/utilisateur/Testdedossier/"
  (dired-filename . "/home/utilisateur/Testdedossier/test.c"))
 ("/home/utilisateur/.emacs.d/config/basicOptimisations.org" . 27)
 ("/home/utilisateur/.emacs.d/config/programmation.org" . 26)
 ("/home/utilisateur/.emacs.d/config/try.org" . 26)
 ("/home/utilisateur/.emacs.d/config/raccourcis.org" . 27)
 ("/home/utilisateur/.emacs.d/config/basicOptimisations.el" . 2734)
 ("/home/utilisateur/.emacs.d/config/programmation.sh" . 278)
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/tel/orgzly/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/tel/orgzly/.."))
 ("/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/tel/"
  (dired-filename . "/home/utilisateur/sharedDirectoryPrivate/sauvegardePcEtTel/tel/.."))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/sujet2"))
 ("/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/sujet2/"
  (dired-filename . "/home/utilisateur/mesdocuments/professionnel/cours/S4/BaseDeDonnees/sujet2/Exercices.org"))
 ("/home/utilisateur/.emacs.d/straight/build/processing-mode/processing-mode-autoloads.el" . 761)
 ("/home/utilisateur/.emacs.d/straight/build/xah-elisp-mode/xah-elisp-mode-autoloads.el" . 1046)
 ("/home/utilisateur/.emacs.d/straight/build/projectile/projectile-autoloads.el" . 21323)
 ("/home/utilisateur/.emacs.d/straight/build/flycheck/flycheck-autoloads.el" . 10429)
 ("/home/utilisateur/.emacs.d/straight/build/let-alist/let-alist-autoloads.el" . 1287)
 ("/home/utilisateur/.emacs.d/straight/build/pkg-info/pkg-info-autoloads.el" . 3763)
 ("/home/utilisateur/.emacs.d/straight/build/epl/epl-autoloads.el" . 261)
 ("/home/utilisateur/.emacs.d/straight/build/yasnippet-snippets/yasnippet-snippets-autoloads.el" . 548)
 ("/home/utilisateur/.emacs.d/straight/build/yasnippet/yasnippet-autoloads.el" . 1847)
 ("/home/utilisateur/.emacs.d/straight/build/company-prescient/company-prescient-autoloads.el" . 1139)
 ("/home/utilisateur/.emacs.d/straight/build/prescient/prescient-autoloads.el" . 297)
 ("/home/utilisateur/.emacs.d/straight/build/company-box/company-box-autoloads.el" . 652)
 ("/home/utilisateur/.emacs.d/straight/build/frame-local/frame-local-autoloads.el" . 309)
 ("/home/utilisateur/.emacs.d/straight/build/company/company-autoloads.el" . 2803)
 ("/home/utilisateur/.emacs.d/straight/build/lsp-java/lsp-java-autoloads.el" . 2092)
 ("/home/utilisateur/.emacs.d/straight/build/dap-mode/dap-mode-autoloads.el" . 10606)
 ("/home/utilisateur/.emacs.d/straight/build/bui/bui-autoloads.el" . 268)
 ("/home/utilisateur/.emacs.d/straight/build/request/request-autoloads.el" . 285)
 ("/home/utilisateur/.emacs.d/straight/build/lsp-treemacs/lsp-treemacs-autoloads.el" . 2278)
 ("/home/utilisateur/.emacs.d/straight/build/treemacs/treemacs-autoloads.el" . 26552)
 ("/home/utilisateur/.emacs.d/straight/build/cfrs/cfrs-autoloads.el" . 416)
 ("/home/utilisateur/.emacs.d/straight/build/posframe/posframe-autoloads.el" . 7930)
 ("/home/utilisateur/.emacs.d/straight/build/pfuture/pfuture-autoloads.el" . 865)
 ("/home/utilisateur/.emacs.d/straight/build/ace-window/ace-window-autoloads.el" . 2190)
 ("/home/utilisateur/.emacs.d/straight/build/lsp-ui/lsp-ui-autoloads.el" . 685)
 ("/home/utilisateur/.emacs.d/straight/build/lsp-mode/lsp-mode-autoloads.el" . 27915)
 ("/home/utilisateur/.emacs.d/straight/build/markdown-mode/markdown-mode-autoloads.el" . 1285)
 ("/home/utilisateur/.emacs.d/straight/build/spinner/spinner-autoloads.el" . 2427)
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/js/jquery-3.3.1.min.js" . 2842)
 ("/home/utilisateur/sharedDirectoryPrivate/org-linkz/js/jquery.searchable.js" . 5827))
